services:

  # Service de base de données MySQL
  valentine-mysql:
    image: mysql:8
    container_name: valentine-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mot de passe pour le root
      MYSQL_DATABASE: valentine_db  # Nom de la base de données
      MYSQL_USER: valentine  # Nom de l'utilisateur non-root
      MYSQL_PASSWORD: valentinepass  # Mot de passe pour l'utilisateur valentine
    ports:
      - "3307:3306"
    volumes:
      - valentine-mysql-data:/var/lib/mysql  # Volume pour la persistance des données
    networks:
      - valentine-infrastructure_backend

  # Service backend
  backend:
    build:
      context: ../valentine-backend
    ports:
      - "8080:80"
    volumes:
      - ../valentine-backend:/var/www/html
    depends_on:
      - valentine-mysql  # Le backend dépend de la base de données
    networks:
      - valentine-infrastructure_backend
    environment:
      DATABASE_URL: mysql://valentine:valentinepass@valentine-mysql:3306/valentine_db

  # Service frontend
  frontend:
    build:
      context: ../valentine-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../valentine-frontend:/app
    depends_on:
      - backend  # Le frontend dépend du backend
    networks:
      - valentine-infrastructure_backend

networks:
  valentine-infrastructure_backend:
    driver: bridge

volumes:
  valentine-mysql-data:
    driver: local